name: LLMChat
options:
  developmentLanguage: en
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: 17.0

targets:
  LLMChat:
    type: application
    platform: iOS
    sources:
      - path: LLMChat
        excludes:
          - Tests/**
    resources:
      - path: LLMChat/Resources
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.LLMChat
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: LLMChat
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: ["UIInterfaceOrientationPortrait"]
        INFOPLIST_KEY_LSRequiresIPhoneOS: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
    scheme:
      testTargets:
        - LLMChatTests

  LLMChatTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - LLMChat/Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.example.LLMChatTests
    dependencies:
      - target: LLMChat